[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 5

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false

[theme]
base = "light"
primaryColor = "#44C1BA"
backgroundColor = "#F7FBF4"
secondaryBackgroundColor = "#C6ECD9"
textColor = "#0B2221"
font = "sans serif"

[runner]
fastReruns = true
magicEnabled = false
